version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: board_app_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: board_local
      DB_USERNAME: board_user
      DB_PASSWORD: board_pass
    depends_on:
      - db
  web:
    image: nginx:1.27-alpine
    container_name: board_app_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
  db:
    image: postgres:15-alpine
    container_name: board_app_db
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: board_local
      POSTGRES_USER: board_user
      POSTGRES_PASSWORD: board_pass
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
